name: CI on Push and Pull Request

on: [push, pull_request]

jobs:
  
  Android:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v3
        
    - name: Install dependencies
      run: nuget restore XamFormsGithubActions/XamFormsGithubActions.NoTest.sln

    - name: Android Build
      run: msbuild XamFormsGithubActions/App1/App1.Android.csproj /verbosity:normal /t:Rebuild /p:Configuration=Release
        
  iOS:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v3
        
    - name: Install dependencies
      run: nuget restore XamFormsGithubActions/XamFormsGithubActions.NoTest.sln
          
    - name: iOS
      run: msbuild XamFormsGithubActions/App1/App1.iOS.csproj /verbosity:normal /t:Rebuild /p:Platform=iPhoneSimulator /p:Configuration=Release

  tests:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup dotnet for Test Project
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: '6.0.x'   
          
    - name: Run Unit Tests
      run: dotnet test XamFormsGithubActions/App1.Test/App1.Test.csproj  /p:Configuration=Release
